# Generated by Django 5.1.2 on 2024-10-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStage',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.FloatField()),
                ('default_exclude_for_leadgen', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('is_meeting_set', models.BooleanField(null=True)),
            ],
        ),
    ]
